-- 1. Create the ad_campaigns table
create table if not exists public.ad_campaigns (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  status text default 'active'::text, -- The missing column causing the 400 error
  end_date timestamp with time zone,
  image_url text,
  link_url text
);

-- 2. Enable RLS
alter table public.ad_campaigns enable row level security;

-- 3. Allow public read access for campaigns
create policy "Allow public read access on ad_campaigns"
on public.ad_campaigns
for select
to public
using (true);