-- 1. Create the listings table if it doesn't exist
create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  category_id text -- Ensure this column exists and matches the IDs in your frontend data
);

-- 2. Enable Row Level Security (RLS) (Highly Recommended)
alter table public.listings enable row level security;

-- 3. Create a policy to allow public read access (Adjust as needed for your app)
create policy "Allow public read access"
on public.listings
for select
to public
using (true);